/**
 * Landmarks on the posed figure, in body units. GENERATED by
 * `npm run hero:geometry` from the MakeHuman base mesh's own joints — do not
 * edit by hand. `heart` and `brain` are placed relative to the spine and head.
 */
export type Point = readonly [number, number, number];

export const LANDMARKS = {
  head: [-0.022, 4.093, -0.059] as Point,
  headTop: [-0.065, 4.946, -0.106] as Point,
  neck: [0.000, 3.445, -0.114] as Point,
  jaw: [0.046, 3.625, 0.695] as Point,
  spine1: [0.000, 2.511, -0.198] as Point,
  spine2: [0.000, 1.595, 0.000] as Point,
  spine3: [0.000, 1.039, -0.066] as Point,
  spine4: [0.000, 0.633, -0.213] as Point,
  pelvis: [0.000, 0.358, -0.069] as Point,
  lClavicle: [0.159, 3.027, 0.260] as Point,
  rClavicle: [-0.159, 3.027, 0.260] as Point,
  lShoulder: [1.003, 3.059, -0.068] as Point,
  rShoulder: [-1.003, 3.059, -0.068] as Point,
  lElbow: [1.254, 1.722, -0.076] as Point,
  rElbow: [-1.324, 1.737, -0.076] as Point,
  lHand: [1.161, 0.392, 0.151] as Point,
  rHand: [-1.359, 0.424, 0.248] as Point,
  lHandTip: [1.080, 0.193, 0.037] as Point,
  rHandTip: [-1.291, 0.212, 0.154] as Point,
  lHip: [0.660, 0.214, -0.082] as Point,
  rHip: [-0.660, 0.214, -0.082] as Point,
  lKnee: [0.748, -2.300, 0.036] as Point,
  rKnee: [-0.805, -2.297, 0.036] as Point,
  lAnkle: [0.939, -4.565, -0.161] as Point,
  rAnkle: [-1.047, -4.558, -0.161] as Point,
  lToe: [0.913, -4.910, 1.059] as Point,
  rToe: [-1.029, -4.903, 1.059] as Point,
  heart: [0.160, 2.191, 0.092] as Point,
  brain: [-0.041, 4.477, -0.060] as Point,
} as const;
